
build_all_linux_x86_64:
  stage: build
  needs: [] 
  script:
    - echo "build all"
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DADD_BASIC_TOOLS=ON -DADD_SDK=ON -DADD_C_LIB=ON -DADD_DYNAMIC_LIB=ON -DADD_PYTHON_MODULE=ON -DADD_QT_APP=ON -DADD_PY_DOCS=ON -DADD_SDK_DOCS=ON -DADD_SCRIPT_TOOLS=ON -DADD_ASSEMBLY_PROGRAM=ON  ..
    - cmake --build . -j 
    - ctest
    - cmake --install .

  artifacts:
    paths:
    - build

  tags:
    - os:linux
    - os:x86_64
