/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TextConversion */

#ifndef _Included_TextConversion
#define _Included_TextConversion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TextConversion
 * Method:    textConversionC
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_TextConversion_textConversionC
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
