/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TextConversionTool */

#ifndef _Included_TextConversionTool
#define _Included_TextConversionTool
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     TextConversionTool
 * Method:    textConversionC
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_TextConversionTool_textConversionC
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
