name: builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code

    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake doxygen

    - name: py dev tools    
      run: python3 -m pip install python-dev-tools

    - name: build directory
      run: mkdir build

    - name: CMake
      run: cmake -DADD_PYTHON_MODULE=ON -DADD_RUST_APP=ON ..
      working-directory: ./build

    - name: build 
      run: cmake --build . --config Release
      working-directory: ./build

    - name: tests
      run: ctest -C Release  -VV
      working-directory: ./build

    - name: collect
      run: cmake --install .
      working-directory: ./build

    - name: lib docs
      run: doxygen build/doxyfile 

    - name: build lib examples
      run: |
        cmake  ../product/lib/example
        cmake --build . --config Release
        ctest -C Release  -VV
      working-directory: ./build/lib_example_build

    - name: test python
      run: python3 -m unittest discover src/test_py
      
    - name: docker
      run: docker build --tag title-case-web .