name: builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code

    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake doxygen qtcreator qtbase5-dev qt5-qmake python3-sphinx cppcheck

    - name: py dev tools    
      run: python3 -m pip install python-dev-tools

    - name: build directory
      run: mkdir build

    - name: CMake
      run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DADD_PYTHON_MODULE=ON -DADD_RUST_APP=ON -DADD_QT_APP=ON ..
      working-directory: ./build

    - name: cppcheck
      run: cppcheck --project=compile_commands.json --cppcheck-build-dir=./temp/cppcheck
      working-directory: ./build

    - name: build 
      run: cmake --build . --config Release
      working-directory: ./build

    - name: tests
      run: ctest -C Release  -VV
      working-directory: ./build

    - name: collect
      run: cmake --install .
      working-directory: ./build

    - name: lib docs
      run: doxygen build/doxyfile

    - name: python module docs
      run: sphinx-build -b html source ../../build/product/python/documentation 
      working-directory: ./src/py_doc

    - name: build lib examples
      run: |
        cmake  ../product/lib/example
        cmake --build . --config Release
        ctest -C Release  -VV
      working-directory: ./build/lib_example_build

    - name: test python
      run: python3 -m unittest discover src/test_py
      
    - name: docker
      run: docker build --tag title-case-web .

    - name: store results
      uses: actions/upload-artifact@v2
      with:
        name: products
        path: build/product
